
package by.amushinsky.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DBInterfaceImplService", targetNamespace = "http://service.amushinsky.by/", wsdlLocation = "http://localhost:8080/company_dbs/dbinterface?wsdl")
public class DBInterfaceImplService
    extends Service
{

    private final static URL DBINTERFACEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException DBINTERFACEIMPLSERVICE_EXCEPTION;
    private final static QName DBINTERFACEIMPLSERVICE_QNAME = new QName("http://service.amushinsky.by/", "DBInterfaceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/company_dbs/dbinterface?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DBINTERFACEIMPLSERVICE_WSDL_LOCATION = url;
        DBINTERFACEIMPLSERVICE_EXCEPTION = e;
    }

    public DBInterfaceImplService() {
        super(__getWsdlLocation(), DBINTERFACEIMPLSERVICE_QNAME);
    }

    public DBInterfaceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DBINTERFACEIMPLSERVICE_QNAME, features);
    }

    public DBInterfaceImplService(URL wsdlLocation) {
        super(wsdlLocation, DBINTERFACEIMPLSERVICE_QNAME);
    }

    public DBInterfaceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DBINTERFACEIMPLSERVICE_QNAME, features);
    }

    public DBInterfaceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DBInterfaceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DBInterface
     */
    @WebEndpoint(name = "DBInterfaceImplPort")
    public DBInterface getDBInterfaceImplPort() {
        return super.getPort(new QName("http://service.amushinsky.by/", "DBInterfaceImplPort"), DBInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DBInterface
     */
    @WebEndpoint(name = "DBInterfaceImplPort")
    public DBInterface getDBInterfaceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.amushinsky.by/", "DBInterfaceImplPort"), DBInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DBINTERFACEIMPLSERVICE_EXCEPTION!= null) {
            throw DBINTERFACEIMPLSERVICE_EXCEPTION;
        }
        return DBINTERFACEIMPLSERVICE_WSDL_LOCATION;
    }

}
