
package by.amushinsky.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DBInterface", targetNamespace = "http://service.amushinsky.by/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DBInterface {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://service.amushinsky.by/DBInterface/addEmployeeRequest", output = "http://service.amushinsky.by/DBInterface/addEmployeeResponse")
    public void addEmployee(
        @WebParam(name = "arg0", partName = "arg0")
        Employee arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://service.amushinsky.by/DBInterface/updateDepartmentRequest", output = "http://service.amushinsky.by/DBInterface/updateDepartmentResponse")
    public void updateDepartment(
        @WebParam(name = "arg0", partName = "arg0")
        Department arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://service.amushinsky.by/DBInterface/deleteDepartmentRequest", output = "http://service.amushinsky.by/DBInterface/deleteDepartmentResponse")
    public void deleteDepartment(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://service.amushinsky.by/DBInterface/addDepartmentRequest", output = "http://service.amushinsky.by/DBInterface/addDepartmentResponse")
    public void addDepartment(
        @WebParam(name = "arg0", partName = "arg0")
        Department arg0);

    /**
     * 
     * @return
     *     returns by.amushinsky.service.DepartmentArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.amushinsky.by/DBInterface/getDepartmentsRequest", output = "http://service.amushinsky.by/DBInterface/getDepartmentsResponse")
    public DepartmentArray getDepartments();

    /**
     * 
     * @return
     *     returns by.amushinsky.service.EmployeeArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.amushinsky.by/DBInterface/getEmployeesRequest", output = "http://service.amushinsky.by/DBInterface/getEmployeesResponse")
    public EmployeeArray getEmployees();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://service.amushinsky.by/DBInterface/deleteEmployeeRequest", output = "http://service.amushinsky.by/DBInterface/deleteEmployeeResponse")
    public void deleteEmployee(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://service.amushinsky.by/DBInterface/updateEmployeeRequest", output = "http://service.amushinsky.by/DBInterface/updateEmployeeResponse")
    public void updateEmployee(
        @WebParam(name = "arg0", partName = "arg0")
        Employee arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns by.amushinsky.service.Department
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.amushinsky.by/DBInterface/getDepartmentRequest", output = "http://service.amushinsky.by/DBInterface/getDepartmentResponse")
    public Department getDepartment(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns by.amushinsky.service.Employee
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.amushinsky.by/DBInterface/getEmployeeRequest", output = "http://service.amushinsky.by/DBInterface/getEmployeeResponse")
    public Employee getEmployee(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

}
